name: CI/CD Pipeline - Docker + EC2 Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout GitHub code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/static-website:latest .

    # Step 4: Push Docker Image to Docker Hub
    - name: Push Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/static-website:latest

    # Step 5: SSH into EC2, Install Docker & Deploy
    - name: Install Docker and Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Updating system..."
          sudo apt update -y

          echo "Checking Docker..."
          if ! command -v docker &> /dev/null
          then
            echo "Installing Docker..."
            sudo apt install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker already installed"
          fi

          echo "Pulling latest image..."
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/static-website:latest

          echo "Stopping old container..."
          sudo docker stop web || true
          sudo docker rm web || true

          echo "Starting new container..."
          sudo docker run -d -p 80:80 --name web \
            ${{ secrets.DOCKER_USERNAME }}/static-website:latest

          echo "Deployment completed successfully"
